### ISSUE TITLE
SA created by driver.sh doens't have permissions to get CRDs

### ISSUE THREAD

**Issue by depohmel** [GoogleCloudPlatform/marketplace-k8s-app-tools#168]
I'm executing driver.sh with 
```
./driver.sh --deployer=gcr.io/kasten-cloudlauncher/k10/deployer:1.1 '--parameters={
  "name": "k10-kasten",
  "reportingSecret": "k10-kasten-reporintg-secret",
  "namespace": "k10-test",
  "serviceAccount.name": "k10-kasten-sa"
}'
```

And getting following error:

```
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4200d7140 0xc4201bf5e0  applications.app.k8s.io /data/resources.yaml 0xc420facc10  false}
from server for: "/data/resources.yaml": customresourcedefinitions.apiextensions.k8s.io "applications.app.k8s.io" is forbidden: User "system:serviceaccount:apptest-bb0609fd:k10-kasten-deployer-sa" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user "system:serviceaccount:apptest-bb0609fd:k10-kasten-deployer-sa"
INFO Deleting namespace "apptest-bb0609fd"
```

**Comment by huyhg** [comment]
I don't think this is an issue anymore, but assigning this to @vcanaa to close the loop.

**Comment by huyhg** [comment]
Just to clarify: SA for the deployer isn't supposed to have access to cluster wide objects like CRD.

**Comment by Ashutosh-Shukla** [comment]
I am facing the same issue where the deployer-sa cannot get/create crd's.
I am deploying an operator which is dependent on crd's. I included the crd in the manifest for it to be created before the operator-deployment. 
Is there any way this can be achieved without manual work as when creating the application from marketplace ui in a new cluster the user will have to create this as an addition step before the operator deployed. 
Maybe I am missing something here, Thanks.
