### ISSUE TITLE
Helm tiller deployer base image

### ISSUE THREAD

**Issue by trironkk** [GoogleCloudPlatform/marketplace-k8s-app-tools#242]
Partner Facing:
* [x]  DEPLOYER_IMAGE x-google-marketplace property for hooks images.
* [ ]  Example repo refactor
* [x] Discontinue pattern of using a wrapper chart - upstream `marketplace-integration` dependency instead.
* [x]  Chart Release Process

Cleanup:
* [ ]  print_config.py support for extracting keys
* [ ]  Application Labels
* [ ]  Add entrypoint.sh to Dockerfile for deployers
* [ ]  Block merging of PRs on integration testing (e.g. `testing/marketplace/deployer/helm_tiller_onbuild`)
* [ ]  Support for original helm deployer
* [x]  Align make target names and directory structure.
* [x]  Clean up testing paradigm within `testing/marketplace/deployer_helm_tiller_base/onbuild`.
* [x]  Investigate deploying to `kube-system` namespace.

**Comment by eshiroma** [comment]
Closing as obsolete since Helm Tiller is deprecated, and #513 tracks deprecating this deployer. Though this issue may help guide some still-needed cleanup.
