### ISSUE TITLE
Feature enablement for Vertical Pod Autoscaler

### ISSUE THREAD

**Issue by techlatest** [GoogleCloudPlatform/marketplace-k8s-app-tools#300]
Please enable Vertical Pod Autoscaler (VPA) for GKE current version.

**Comment by huyhg** [comment]
GKE currently does support 1.11, where VPA is in beta and can be used.

The default version of a new GKE cluster is still 1.10; so if you're creating a new cluster, make sure to select 1.11.

Please re-open this issue if this isn't the answer you're looking for. Thanks!
