### ISSUE TITLE
Use fully qualified CRD name in deploy scripts

### ISSUE THREAD

**Issue by vkamra** [GoogleCloudPlatform/marketplace-k8s-app-tools#321]
Deploy scripts that reference the Applications CRD (or others) should use the full resource name i.e. `applications.app.k8s.io` instead of `applications` .

The latter conflicts with any resource named `applications` in a different API group e.g. `applications.<customer api group>` and will break any marketplace deploys in that environment.

https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/scripts/watch.sh#L46 is an example which should be hardened.

**Comment by vkamra** [comment]
@huyhg - could you help triage ^^. Happy to submit a PR also.

**Comment by huyhg** [comment]
@vkamra Thanks for the report! More than happy to take a PR.

**Comment by vkamra** [comment]
> @vkamra Thanks for the report! More than happy to take a PR.

👍 - Pushed a PR.
