### ISSUE TITLE
Remove flag that adds additional role binding to deployer

### ISSUE THREAD

**Issue by vcanaa** [GoogleCloudPlatform/marketplace-k8s-app-tools#344]
Some deployers running in test mode need cluster wide access, which is more powerful than the official namespace access. In order to unblock verification for these particular apps, a flag for adding additional role bindings was introduced.

This flag can be removed once verification does not require cluster wide access for these apps.

**Comment by eshiroma** [comment]
Verification is expected to leverage the same execution model.
