### ISSUE TITLE
ServiceAccounts do not own ClusterRoles in 0.9.6

### ISSUE THREAD

**Issue by DTMad** [GoogleCloudPlatform/marketplace-k8s-app-tools#443]
Hey!

When deploying a deployer with a schema.yaml file which consists ServiceAccounts with ClusterRoles underneath with mpdev the ServiceAccounts won't own the ClusterRoles after creation.
The problem is not the 'does not own' but the ClusterRoles do not get created at all.

This most probably happens because of that:
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/9a00f6384e6fa135cdd8ea7d2ba695c8b8246166/marketplace/deployer_util/set_ownership.py#L143
The 'continue' there skips the 'to_be_dumped.append(resource)' underneath.

Occurs in v0.9.6
Does not occur in v0.9.5

**mpdev output in v0.9.6:**
`Using /opt/kubectl/1.13/kubectl (server=1.13)
Using /opt/kubectl/1.13/kubectl (server=1.13)
application.app.k8s.io/dynatrace-oneagent-operator created
Using /opt/kubectl/1.13/kubectl (server=1.13)
INFO Application 'xxx' owns 'ServiceAccount/xxx-operatorserviceaccount'
INFO Application 'xxx' owns 'Role/xxx:operatorServiceAccount-r0'
INFO Application 'xxx' owns 'RoleBinding/xxx:operatorServiceAccount-rb0'
INFO Application 'xxx' does not own cluster-scoped 'ClusterRole/xxx:xxx:operatorServiceAccount-r0'
INFO Application 'xxx' does not own cluster-scoped 'ClusterRoleBinding/xxx:xxx:operatorServiceAccount-rb0'  INFO Application 'xxx' owns 'ServiceAccount/xxx-crdserviceaccount'
INFO Application 'xxx' does not own cluster-scoped 'ClusterRole/xxx:crdServiceAccount-r0'
INFO Application 'xxx' does not own cluster-scoped 'ClusterRoleBinding/xxx:xxx:crdServiceAccount-rb0'       INFO Application 'xxx' owns 'ServiceAccountxxx'
INFO Application 'xxx' owns 'Role/xxx:oneagentServiceAccount-r0'
INFO Application 'xxx' owns 'RoleBinding/xxx:oneagentServiceAccount-rb0'
INFO Application 'xxx' owns 'ServiceAccount/xxx-deployer-sa'
INFO Application 'xxx' owns 'ConfigMap/xxx-deployer-config'
INFO Application 'xxx' owns 'Job/xxx-deployer'
INFO Application 'xxx' owns 'RoleBinding/xxx-deployer-rb'
Using /opt/kubectl/1.13/kubectl (server=1.13)
...`

**mpdev output in v0.9.5:**
`Using /opt/kubectl/1.13/kubectl (server=1.13)
Using /opt/kubectl/1.13/kubectl (server=1.13)
application.app.k8s.io/xxx created
Using /opt/kubectl/1.13/kubectl (server=1.13)
INFO Application 'xxx' owns 'ServiceAccount/xxx-operatorserviceaccount'
INFO Application 'xxx' owns 'Role/xxx:operatorServiceAccount-r0'
INFO Application 'xxx' owns 'RoleBinding/xxx:operatorServiceAccount-rb0'
INFO Application 'xxx' owns 'ClusterRole/dynatrace:xxx:operatorServiceAccount-r0'
INFO Application 'xxx' owns 'ClusterRoleBinding/dynatrace:xxx:operatorServiceAccount-rb0'
INFO Application 'xxx' owns 'ServiceAccount/xxx-crdserviceaccount'
INFO Application 'xxx' owns 'ClusterRole/dynatrace:xxx:crdServiceAccount-r0'
INFO Application 'xxx' owns 'ClusterRoleBinding/dynatrace:xxx:crdServiceAccount-rb0'
INFO Application 'xxx' owns 'ServiceAccount/xxx-oneagentserviceaccount'
INFO Application 'xxx' owns 'Role/xxx:oneagentServiceAccount-r0'
INFO Application 'xxx' owns 'RoleBinding/xxx:oneagentServiceAccount-rb0'
INFO Application 'xxx' owns 'ServiceAccount/xxx-deployer-sa'
INFO Application 'xxx' owns 'ConfigMap/xxx-deployer-config'
INFO Application 'xxx' owns 'Job/xxx-deployer'
INFO Application 'xxx' owns 'RoleBinding/xxx-deployer-rb'
Using /opt/kubectl/1.13/kubectl (server=1.13)
...`

**Comment by eshiroma** [comment]
Thanks for the detailed report and bug find - creating a fix.

**Comment by eshiroma** [comment]
(This issue should is fixed in release [0.9.8](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/releases/tag/0.9.8))
