### ISSUE TITLE
/bin/docker_entrypoint.sh: line 21: /scripts/doctor.py: No such file or directory

### ISSUE THREAD

**Issue by Ygshvr** [GoogleCloudPlatform/marketplace-k8s-app-tools#451]
When I am running the `mpdev /scripts/doctor.py` command and I am getting this error:
`/bin/docker_entrypoint.sh: line 21: /scripts/doctor.py: No such file or directory` .

On further looking into the issue I found that the marketplace tool's latest image (gcr.io/cloud-marketplace-tools/k8s/dev) has removed the .py extension from the /scripts/doctor.py file. I am not sure why someone did that but either the [document](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/tool-prerequisites.md#running-the-doctor-tool) needs to be updated to use the command `mpdev /scripts/doctor` from `mpdev /scripts/doctor.py` for checking the environment setup or the docker image should be updated with the correct file name.

**Comment by eshiroma** [comment]
Thanks for pointing out this issue. The script was renamed for simplicity but that piece of documentation was missed in #324. Fixing the documentation in #455.
