### ISSUE TITLE
Add support for Helm v3 test hook

### ISSUE THREAD

**Issue by Nana-EC** [GoogleCloudPlatform/marketplace-k8s-app-tools#569]
Currently the [process_helm_hooks.py](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/marketplace/deployer_util/process_helm_hooks.py) only supports the `helm.sh/hook: test-success` hook from Helm v2.
In v3 as highlighted in the [Chart Tests](https://helm.sh/docs/topics/chart_tests/), users can now use the simpler `helm.sh/hook: test` form.

Devs using the v3 format currently hit the following exception when using `mpdev` and are forced to change to the v2 format to progress
```
"Helm hook test is not supported"
```

To allow easy support for marketplace devs using Helm v3 could we

- Add support for `helm.sh/hook: test` to `marketplace-k8s-app-tools/marketplace/deployer_util/process_helm_hooks.py`

**Comment by justmike1** [comment]
#612

**Comment by gibbleyg** [comment]
This should be fixed in https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/releases/tag/0.12.0
